import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Flag, Gauge, ShieldCheck, Star, Trophy, Users } from 'lucide-react'
import { motorsportRepository } from '../../data/motorsportRepository'
import { useAuth } from '../../auth/AuthProvider'
import { addFavorite, listFavorites, removeFavorite } from '../../lib/userData'
import type { EntityKind, MotorsportCatalog, RaceResult } from '../../types/domain'

type Props = { kind: EntityKind; id: string; onBack: () => void }

export function EntityDetails({ kind, id, onBack }: Props) {
  const { user } = useAuth()
  const [catalog, setCatalog] = useState<MotorsportCatalog | null>(null)
  const [results, setResults] = useState<RaceResult[]>([])
  const [favorite, setFavorite] = useState(false)
  useEffect(() => { let active = true; motorsportRepository.getCatalog().then((next) => { if (active) setCatalog(next) }); motorsportRepository.getSeasonData().then((next) => { if (active && next) setResults(next.results) }); return () => { active = false } }, [])
  useEffect(() => { if (!user) return; void listFavorites(user.id).then((items) => setFavorite(items.some((item) => item.entity_type === kind && item.entity_id === id))).catch(() => undefined) }, [user, kind, id])
  const entity: any = useMemo(() => { if (!catalog) return null; if (kind === 'driver') return catalog.drivers.find((item) => item.id === id) ?? null; if (kind === 'team') return catalog.teams.find((item) => item.id === id) ?? null; if (kind === 'race') return catalog.races.find((item) => item.id === id) ?? null; return catalog.circuits.find((item) => item.id === id) ?? null }, [catalog, kind, id])
  const related = useMemo(() => { if (!catalog || !entity) return { rows: [] as RaceResult[], title: '' }; if (kind === 'driver') return { rows: results.filter((row) => row.driverId === id), title: 'Race results' }; if (kind === 'team') return { rows: results.filter((row) => row.teamId === id), title: 'Team race results' }; if (kind === 'race') return { rows: results.filter((row) => row.raceId === id), title: 'Race classification' }; const raceIds = new Set(catalog.races.filter((race) => race.circuitId === id).map((race) => race.id)); return { rows: results.filter((row) => raceIds.has(row.raceId)), title: 'Circuit race results' } }, [catalog, entity, kind, id, results])
  const toggleFavorite = async () => { if (!user) return; const next = !favorite; setFavorite(next); try { if (next) await addFavorite(user.id, kind, id); else await removeFavorite(user.id, kind, id) } catch { setFavorite(!next) } }
  if (!catalog || !entity) return <main className="content"><section className="dashboard-state"><p>Loading verified entity data...</p></section></main>
  const title = 'fullName' in entity ? entity.fullName : entity.name
  const meta = kind === 'driver' ? [entity.nationality, 'number' in entity ? entity.number ? `#${entity.number}` : 'No number' : ''].filter(Boolean).join(' · ') : kind === 'team' ? [entity.country, entity.shortName].join(' · ') : kind === 'race' ? [`Round ${String(entity.round).padStart(2, '0')}`, entity.date ?? 'Date unavailable'].join(' · ') : [entity.location, entity.country, 'laps' in entity && entity.laps ? `${entity.laps} laps` : 'Laps unavailable'].join(' · ')
  const status = entity.status === 'verified' ? 'VERIFIED DATA' : 'PREVIEW DATA'
  return <main className="content entity-details-page"><button className="back-link" onClick={onBack}><ArrowLeft size={16} /> Back to catalog</button><section className="entity-hero"><div><p className="eyebrow">{kind.toUpperCase()} / {status}</p><h1>{title}</h1><p className="entity-meta">{meta}</p></div><button className={favorite ? 'favorite-detail active' : 'favorite-detail'} onClick={() => void toggleFavorite()} aria-pressed={favorite}><Star size={18} fill={favorite ? 'currentColor' : 'none'} /> {favorite ? 'Saved' : 'Save'}</button></section><section className="entity-grid"><article className="panel entity-summary"><div className="panel-heading"><div><p className="eyebrow">ENTITY PROFILE</p><h2>Overview</h2></div><ShieldCheck size={18} /></div><div className="entity-facts"><div><span>Status</span><strong>{status}</strong></div><div><span>Season</span><strong>{catalog.season}</strong></div>{kind === 'driver' && <div><span>Team</span><strong>{catalog.teams.find((team) => team.id === entity.teamId)?.name ?? '—'}</strong></div>}{kind === 'race' && <div><span>Circuit</span><strong>{catalog.circuits.find((circuit) => circuit.id === entity.circuitId)?.name ?? entity.circuitId}</strong></div>}{kind === 'circuit' && <div><span>Races in catalog</span><strong>{catalog.races.filter((race) => race.circuitId === entity.id).length}</strong></div>}{kind === 'team' && <div><span>Drivers in catalog</span><strong>{catalog.drivers.filter((driver) => driver.teamId === entity.id).length}</strong></div>}</div></article><article className="panel entity-summary"><div className="panel-heading"><div><p className="eyebrow">DATA RELATION</p><h2>{related.title}</h2></div><Gauge size={18} /></div>{related.rows.length ? <div className="entity-results">{related.rows.slice(0, 10).map((row) => <div className="entity-result-row" key={row.id}><span>{kind === 'race' ? `P${row.position ?? '—'}` : `Round ${String(row.round).padStart(2, '0')}`}</span><strong>{row.points} pts</strong><small>{row.status} · {row.grid ? `Grid ${row.grid}` : 'Grid —'}</small></div>)}</div> : <div className="empty-state">No verified race results are available for this entity yet.</div>}</article></section><section className="entity-stat-strip"><div><Trophy size={17}/><span>Results loaded</span><strong>{related.rows.length}</strong></div><div><Flag size={17}/><span>Entity type</span><strong>{kind}</strong></div><div><Users size={17}/><span>Source</span><strong>Jolpica</strong></div></section></main>
}